openapi: 3.2.0
info:
  title: Restaurants Groups API
  description: Returns information about the configuration of restaurant.
  version: 1.0.0
  contact:
    name: Toast developer support
servers:
- url: https://toast-api-server/restaurants/v1
tags:
- name: Groups
paths:
  /groups/{managementGroupGUID}/restaurants:
    get:
      operationId: groupsManagementGroupGuidRestaurantsGet
      summary: Toast Get Restaurants in a Management Group
      description: 'Returns an array of `Restaurant` objects that are a part of the

        restaurant management group you specify in the

        `managementGroupGUID` path parameter. Each `Restaurant` object

        contains the unique Toast platform identifier for the restaurant in

        its `guid` value.'
      parameters:
      - name: managementGroupGUID
        in: path
        description: 'The GUID of the restaurant management group.

          '
        required: true
        schema:
          type: string
      - name: Toast-Restaurant-External-ID
        description: "The Toast GUID of one restaurant location in the management \ngroup.\n"
        in: header
        required: true
        schema:
          type: string
          format: string
      responses:
        '200':
          description: 'An array of `Restaurant` objects.

            '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
      security:
      - oauth2:
        - restaurants:read
      tags:
      - Groups
components:
  schemas:
    Restaurant:
      type: object
      description: 'The Toast POS GUID for a restaurant

        '
      properties:
        guid:
          type: string
          description: 'The unique identifier that the Toast POS assigns to a

            restaurant.

            '
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          scopes:
            restaurants:read: 'Allows reading from the restaurants API.

              '
          tokenUrl: https://toast-api-server/authentication/v1/authentication/login
      description: "Access to Toast APIs, specific endpoints, \nand specific API endpoint operations is \ncontrolled by the scopes that are associated \nwith your API account. \nA full reference for Toast API scopes and \ntheir capabilities can be found in the\n[_Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiScopes.html).\n"
